sudo: false
language: c

addons:
  apt:
    packages:
    - DruidBarClassic

script: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash

branches:
  only:
  - /.*/
